# Generated by Django 2.2.2 on 2019-06-24 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voluntario',
            fields=[
                ('nombre', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('rut', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('edad', models.IntegerField()),
                ('celular', models.IntegerField()),
                ('comuna', models.CharField(max_length=50)),
                ('fecha_nac', models.CharField(max_length=15)),
                ('ocupacion', models.CharField(max_length=50)),
                ('nivel_educacion', models.CharField(max_length=50)),
                ('grupo_interes', models.CharField(max_length=50)),
            ],
        ),
    ]
