# Generated by Django 2.2.2 on 2019-06-25 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fundacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voluntario',
            name='grupo_interes',
        ),
        migrations.RemoveField(
            model_name='voluntario',
            name='nivel_educacion',
        ),
        migrations.RemoveField(
            model_name='voluntario',
            name='ocupacion',
        ),
    ]
