# Generated by Django 2.2.6 on 2019-10-26 04:03

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('fundacion', '0002_voluntario_fecha_incripcion'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='voluntario',
            managers=[
                ('voluntarios', django.db.models.manager.Manager()),
            ],
        ),
    ]
