# Generated by Django 2.2.2 on 2019-06-25 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundacion', '0003_remove_voluntario_fecha_nac'),
    ]

    operations = [
        migrations.AddField(
            model_name='voluntario',
            name='fecha',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='voluntario',
            name='celular',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='voluntario',
            name='edad',
            field=models.CharField(max_length=50),
        ),
    ]
