# Generated by Django 2.1.7 on 2019-09-13 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voluntario',
            name='fecha_incripcion',
            field=models.CharField(default='2019-09-12', max_length=15),
            preserve_default=False,
        ),
    ]
