# Generated by Django 2.2.5 on 2019-09-12 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voluntario',
            fields=[
                ('nombre', models.CharField(max_length=50)),
                ('rut', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('fecha', models.CharField(max_length=50)),
                ('edad', models.CharField(max_length=50)),
                ('celular', models.CharField(max_length=50)),
                ('comuna', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
