# Generated by Django 2.2.6 on 2019-11-13 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundacion', '0003_auto_20191111_0253'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='logo',
            field=models.FileField(default='SOME STRING', upload_to=''),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='descripcion',
            field=models.CharField(max_length=200),
        ),
    ]
