# Generated by Django 2.2.6 on 2019-11-13 06:37

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('fundacion', '0004_auto_20191113_0322'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='proyecto',
            managers=[
                ('proyectos', django.db.models.manager.Manager()),
            ],
        ),
    ]
