# Generated by Django 2.2.6 on 2019-11-14 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fundacion', '0005_auto_20191113_0337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='cantidad_voluntarios',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='logo',
        ),
    ]
