# Generated by Django 2.2.6 on 2019-11-14 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundacion', '0006_auto_20191114_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='cantidad_voluntarios',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proyecto',
            name='descripcion',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proyecto',
            name='logo',
            field=models.FileField(default='SOME STRING', upload_to=''),
        ),
    ]
