# Generated by Django 2.2.6 on 2019-11-22 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundacion', '0007_auto_20191114_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='voluntario',
            name='proyecto_actividad',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='cantidad_voluntarios',
            field=models.IntegerField(blank=True),
        ),
    ]
