# Generated by Django 2.2.7 on 2019-11-25 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundacion', '0009_auto_20191125_0432'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='id_proyecto',
            field=models.IntegerField(default=0),
        ),
    ]
