# Generated by Django 2.2.5 on 2019-11-26 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fundacion', '0010_usuario_id_proyecto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='logo',
        ),
    ]
